version: "3.8"

services:
  test_admin:
    container_name: test_admin
    environment:
      - TZ="Europe/Moscow"
    build:
      context: ./test_admin
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:3000:3000
    restart: always

  test_client:
    container_name: test_client
    environment:
      - TZ="Europe/Moscow"
    build:
      context: ./test_clientD
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:3001:3001
    restart: always
