version: "3.8"

services:
  test_admin:
    container_name: test_admin
    environment:
      - TZ="Europe/Moscow"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:3000:3000
    restart: always
